### ISSUE TITLE
Add Link to Original Issue

### ISSUE THREAD

**Issue by blaiszik** [blaiszik/moment#8]
In the latest PR, @bdecost added capability to display details of aggregated issues. We should also provide a direct link to the collected issues. Looks great though!

**Comment by bdecost** [comment]
What sort of behavior would be interesting? The Issues link at the right lands on the main issues page, which I think is great

- The issue title should probably link to that issue's page, as in https://github.com/bdecost/moment-test1/issues/1
- The issue label badges could link to filtered issue pages, as in https://github.com/bdecost/moment-test1/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
- If we have Moment track only issues with certain labels, maybe a link somewhere to land on the GH filtered issue page for that set of issues? (vs the Issues button at the right of the display which links to all open issues)

**Comment by blaiszik** [comment]
We might also want a view that allows a user to see all issues matching a tag across projects (e.g., `good first issue`) . But, that will add some complexity and I think that it can wait for now...

Maybe we should also consider promoting usage of domain keywords to help users find based on their interests:
e.g., 
`materials-science`
`chemistry`
`data infrastructure`

**Comment by bdecost** [comment]
agreed, filtering by label on the Moment project or issue view would be a great cross-repository tool for finding opportunities. With the static site I think it will require some js, like https://lunrjs.com or something similar. Personally I don't have any direct js experience so I'm not entirely sure what a reasonable solution is.

I like the idea of domain keywords -- is that a good use case for encouraging use of github topics for repositories, as in https://github.com/topics/materials-science ?

Something like `materials-science` seems too broad for an issue-level label, but perhaps `data-infrastructure` could serve as both a repo-level topic and a specific issue label within a more general scientific project repo

Side note, I really like that this idea of Moment effectively largely maps to using github collaboration features effectively

**Comment by blaiszik** [comment]
Closing with latest PR merge, and creating a new issue based on the last comments
